POST http://localhost:3003/exercises
Content-Type: application/json

{
  "daily_exercises": [3, 0, 2, 4.5, 0, 3, 1]
}

# Expected response
# HTTP/1.1 400 Bad Request
# Content-Type: application/json  

# {
#   "error": "parameters missing"
# }