POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "Frank Lucas",
  "dateOfBirth": "2000-01-01",
  "ssn": "010100-123A",
  "gender": "male",
  "occupation": "drug lord"
}
